language: node_js
node_js:
  - "12"

notifications:
  email: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - nvm use v12.0.0

install:
  - npm ci

cache:
  directories:
    - node_modules

before_script:
  - npm install
  - npm npm install -g gulp-cli
  - npm install forever -g

script:
  - gulp production
  - npm start webrtcserver.js

deploy:
  - provider: npm
  - email: "tara181989@gmail.com"
      - tag: next
  - on:
      - branch: all
      - tags: true